### ISSUE TITLE
Descriptive Readme file 

### ISSUE THREAD

**Issue by tanzila-abedin** [Marwen-Brini/project1#2]
Hey Marwin.

Thank you for sharing your first Microverse project with the rest of the Yoketrons team. 
I am submitting this issue because it's part of the morning peer-to-peer review task.  I suppose you have already received your code review from the TSEs so there's no need for us to leave feedback on your code.  

But there's something you can add to make your project repo look more organized. Please add a descriptive Readme file and in the file put a link to show your project live. 

I'm leaving a link down below of general requirements for Microverse projects. You can have a look.

(https://microverse.zendesk.com/hc/en-us/articles/360057489093-General-Requirements-for-Microverse-Projectsurl)

**Comment by Marwen-Brini** [comment]
thank you tanzila, i've corrected the mistake in branch3 and i'm awaiting the reviewer's confirmation for the merge

**Comment by Marwen-Brini** [comment]
issue solved
